swiftmailer:

    spool:     { type: memory }

    url:

    transport: smtp
    host:      mail.gandi.net
    username:  noreply@pix.city
    password:  pMla78Mns9#6QmbcA
    auth_mode: login
    port: 465
    encryption: ssl

    stream_options:
        ssl:
            verify_peer: false
            verify_peer_name: false
            allow_self_signed: true
